Repository asdsyd/Healthy-developer, pull requests merged in 2022-10, with the labels that each got.

#3 updating readme to describing some point
  README.md
Labels: documentation, hacktoberfest

#10 Create Code of Conduct.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest

#11 Create explore.html page with 9 new cards
  explore.html
Labels: enhancement, hacktoberfest

#13 Update index.html to redirect explore button to resp. page
  index.html
Labels: bug, good first issue, hacktoberfest

#17 Added Contact Page
  assets/contact.css
  contact.html
  index.html
Labels: enhancement, good first issue, hacktoberfest

#20 Completed the contact us page
  assets/contact.css
  contact.html
  index.html
Labels: enhancement, hacktoberfest

#21 Fix contact-page render issue#19
  contact.html
  package-lock.json
Labels: bug, good first issue, hacktoberfest

#33 moved index.html
  index.html
  src/input.css
Labels: bug, hacktoberfest

#36 Update README.md
  README.md
Labels: hacktoberfest

#37 design of healthy developer
  healthy developer/Frame 11 (1).png
  healthy developer/Frame 11.png
Labels: hacktoberfest

#39 changed title
  index.html
Labels: enhancement, hacktoberfest

#40 Update README.md
  README.md
Labels: hacktoberfest

#48 footer added to the site
  .vscode/settings.json
  index.html
  src/assets/style.css
Labels: good first issue, hacktoberfest

#51 Updating the testing branch on par with the main branch
  .gitignore
  .vscode/settings.json
  README.md
  contact.html
  healthy developer/Frame 11 (1).png
  healthy developer/Frame 11.png
  index.html
  package-lock.json
  package.json
  src/assets/about.css
  src/assets/contact.css
  src/assets/faq.css
  src/assets/style.css
  src/pages/about.html
  src/pages/contact.html
  src/pages/explore.html
  src/pages/faq.html
  tailwind.config.js
Labels: hacktoberfest

#56 file removed
  README.md
  healthy-developer/Frame 11 (1).png
  healthy-developer/Frame.png
Labels: documentation, invalid, hacktoberfest

#57 D fix
  README.md
Labels: documentation, hacktoberfest, spam

#61 Improved FAQ.html and added question mark to all questions
  index.html
  src/pages/faq.html
Labels: enhancement, good first issue, hacktoberfest, low-code

#69 Fixed Header Menu At FAQ and Added Menu at Other Pages
  src/assets/about.css
  src/assets/contact.css
  src/assets/faq.css
  src/assets/style.css
  src/pages/about.html
  src/pages/contact.html
  src/pages/faq.html
Labels: enhancement, hacktoberfest

#73 Made Footer Fixed in Bottom and Fixed Menu
  src/assets/about.css
  src/assets/contact.css
  src/assets/faq.css
  src/assets/style.css
  src/pages/about.html
  src/pages/contact.html
  src/pages/faq.html
Labels: bug, enhancement, hacktoberfest
